import { Task } from "@/types/task";
import { Project } from "@/types/project";
import { Decision, DecisionVote } from "@/types/decision";

function formatDate(dateStr: string | null): string {
  if (!dateStr) return "—";
  return new Date(dateStr).toLocaleDateString("en-NG", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function openPrintWindow(html: string) {
  const win = window.open("", "_blank", "width=800,height=600");
  if (!win) {
    alert("Please allow popups to export reports.");
    return;
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}

const PRINT_CSS = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 24px; color: #111827; font-size: 13px; line-height: 1.5; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 4px; }
  h2 { font-size: 16px; font-weight: 600; margin: 24px 0 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
  .subtitle { color: #6b7280; font-size: 13px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th { text-align: left; font-weight: 600; padding: 6px 8px; border-bottom: 2px solid #e5e7eb; font-size: 11px; text-transform: uppercase; color: #6b7280; }
  td { padding: 6px 8px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 500; color: #fff; }
  .meta { color: #9ca3af; font-size: 11px; margin-top: 32px; border-top: 1px solid #e5e7eb; padding-top: 8px; }
  @media print { body { padding: 0; } }
`;

function printPage(title: string, bodyHtml: string) {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title><style>${PRINT_CSS}</style></head><body>${bodyHtml}<div class="meta">Generated by NAVO HQ on ${new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" })}</div></body></html>`;
  openPrintWindow(html);
}

export function printTaskReport(tasks: Task[]) {
  const rows = tasks
    .map(
      (t) => `
    <tr>
      <td>${escapeHtml(t.title)}</td>
      <td><span class="badge" style="background:${t.status?.color || "#9CA3AF"}">${escapeHtml(t.status?.name || "Unknown")}</span></td>
      <td><span class="badge" style="background:${t.priority?.color || "#9CA3AF"}">${escapeHtml(t.priority?.name || "Unknown")}</span></td>
      <td>${escapeHtml(t.owner?.name || "Unassigned")}</td>
      <td>${escapeHtml(t.project?.name || "—")}</td>
      <td>${formatDate(t.due_date)}</td>
    </tr>`
    )
    .join("");

  printPage("Task Report", `
    <h1>Task Report</h1>
    <p class="subtitle">${tasks.length} task${tasks.length !== 1 ? "s" : ""} &middot; ${new Date().toLocaleDateString("en-NG")}</p>
    <table>
      <thead><tr><th>Title</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Project</th><th>Due Date</th></tr></thead>
      <tbody>${rows || "<tr><td colspan='6' style='text-align:center;color:#9ca3af'>No tasks</td></tr>"}</tbody>
    </table>
  `);
}

export function printProjectReport(project: Project, tasks: Task[]) {
  const stats = project.task_stats || { total: 0, done: 0, in_progress: 0, blocked: 0, overdue: 0 };

  const rows = tasks
    .map(
      (t) => `
    <tr>
      <td>${escapeHtml(t.title)}</td>
      <td><span class="badge" style="background:${t.status?.color || "#9CA3AF"}">${escapeHtml(t.status?.name || "Unknown")}</span></td>
      <td><span class="badge" style="background:${t.priority?.color || "#9CA3AF"}">${escapeHtml(t.priority?.name || "Unknown")}</span></td>
      <td>${escapeHtml(t.owner?.name || "Unassigned")}</td>
      <td>${formatDate(t.due_date)}</td>
    </tr>`
    )
    .join("");

  printPage(project.name, `
    <h1>${escapeHtml(project.name)}</h1>
    <p class="subtitle">${escapeHtml(project.description || "")} &middot; ${project.status?.name || ""}</p>

    <h2>Project Summary</h2>
    <table>
      <tbody>
        <tr><td><strong>Status</strong></td><td>${escapeHtml(project.status?.name || "—")}</td></tr>
        <tr><td><strong>Owner</strong></td><td>${escapeHtml(project.owner?.name || "—")}</td></tr>
        <tr><td><strong>Start Date</strong></td><td>${formatDate(project.start_date)}</td></tr>
        <tr><td><strong>Target Date</strong></td><td>${formatDate(project.target_date)}</td></tr>
        <tr><td><strong>Total Tasks</strong></td><td>${stats.total}</td></tr>
        <tr><td><strong>Completed</strong></td><td>${stats.done}</td></tr>
        <tr><td><strong>In Progress</strong></td><td>${stats.in_progress}</td></tr>
        <tr><td><strong>Overdue</strong></td><td>${stats.overdue}</td></tr>
      </tbody>
    </table>

    <h2>Tasks (${tasks.length})</h2>
    <table>
      <thead><tr><th>Title</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Due Date</th></tr></thead>
      <tbody>${rows || "<tr><td colspan='5' style='text-align:center;color:#9ca3af'>No tasks</td></tr>"}</tbody>
    </table>
  `);
}

export function printDecisionReport(decision: Decision, votes: DecisionVote[]) {
  const approve = votes.filter((v) => v.vote === "approve").length;
  const reject = votes.filter((v) => v.vote === "reject").length;
  const abstain = votes.filter((v) => v.vote === "abstain").length;

  const voteRows = votes
    .map(
      (v) => `
    <tr>
      <td>${escapeHtml(v.user?.name || "Unknown")}</td>
      <td><span class="badge" style="background:${v.vote === "approve" ? "#22c55e" : v.vote === "reject" ? "#ef4444" : "#9ca3af"}">${v.vote}</span></td>
      <td>${escapeHtml(v.comment || "—")}</td>
    </tr>`
    )
    .join("");

  const sections = [
    { label: "Context", value: decision.context },
    { label: "Proposed Decision", value: decision.proposed_decision },
    { label: "Decision Text", value: decision.decision_text },
    { label: "Reason", value: decision.reason },
    { label: "Alternatives", value: decision.alternatives },
  ]
    .filter((s) => s.value)
    .map((s) => `<h2>${escapeHtml(s.label)}</h2><p style="white-space:pre-wrap">${escapeHtml(s.value!)}</p>`)
    .join("");

  printPage(decision.title, `
    <h1>${escapeHtml(decision.title)}</h1>
    <p class="subtitle">${escapeHtml(decision.topic || "")} &middot; ${decision.status?.name || ""} &middot; Created ${formatDate(decision.created_at)}</p>

    ${sections}

    <h2>Vote Results</h2>
    <table>
      <tbody>
        <tr><td><strong>Approve</strong></td><td>${approve}</td></tr>
        <tr><td><strong>Reject</strong></td><td>${reject}</td></tr>
        <tr><td><strong>Abstain</strong></td><td>${abstain}</td></tr>
      </tbody>
    </table>

    <h2>Individual Votes (${votes.length})</h2>
    <table>
      <thead><tr><th>Voter</th><th>Vote</th><th>Comment</th></tr></thead>
      <tbody>${voteRows || "<tr><td colspan='3' style='text-align:center;color:#9ca3af'>No votes yet</td></tr>"}</tbody>
    </table>
  `);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
